/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiAccessRouteImport } from './routes/api-access'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTierRequestsRouteImport } from './routes/admin.tier-requests'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTierRequestsRoute = AdminTierRequestsRouteImport.update({
  id: '/admin/tier-requests',
  path: '/admin/tier-requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/api-access': typeof ApiAccessRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/submit': typeof SubmitRoute
  '/team': typeof TeamRoute
  '/admin/tier-requests': typeof AdminTierRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/api-access': typeof ApiAccessRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/submit': typeof SubmitRoute
  '/team': typeof TeamRoute
  '/admin/tier-requests': typeof AdminTierRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/api-access': typeof ApiAccessRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/monitoring': typeof MonitoringRoute
  '/organizations': typeof OrganizationsRoute
  '/pricing': typeof PricingRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/submit': typeof SubmitRoute
  '/team': typeof TeamRoute
  '/admin/tier-requests': typeof AdminTierRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/api-access'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/insights'
    | '/map'
    | '/monitoring'
    | '/organizations'
    | '/pricing'
    | '/register-organization'
    | '/reports'
    | '/reset-password'
    | '/submit'
    | '/team'
    | '/admin/tier-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/api-access'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/insights'
    | '/map'
    | '/monitoring'
    | '/organizations'
    | '/pricing'
    | '/register-organization'
    | '/reports'
    | '/reset-password'
    | '/submit'
    | '/team'
    | '/admin/tier-requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/api-access'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/insights'
    | '/map'
    | '/monitoring'
    | '/organizations'
    | '/pricing'
    | '/register-organization'
    | '/reports'
    | '/reset-password'
    | '/submit'
    | '/team'
    | '/admin/tier-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiAccessRoute: typeof ApiAccessRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  MonitoringRoute: typeof MonitoringRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PricingRoute: typeof PricingRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubmitRoute: typeof SubmitRoute
  TeamRoute: typeof TeamRoute
  AdminTierRequestsRoute: typeof AdminTierRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-access': {
      id: '/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tier-requests': {
      id: '/admin/tier-requests'
      path: '/admin/tier-requests'
      fullPath: '/admin/tier-requests'
      preLoaderRoute: typeof AdminTierRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiAccessRoute: ApiAccessRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  MonitoringRoute: MonitoringRoute,
  OrganizationsRoute: OrganizationsRoute,
  PricingRoute: PricingRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubmitRoute: SubmitRoute,
  TeamRoute: TeamRoute,
  AdminTierRequestsRoute: AdminTierRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
